all:
	g++ client.cpp -g -std=c++11 -o client
	g++ serverC.cpp -g -std=c++11 -o serverC
	g++ serverCS.cpp -g -std=c++11 -o serverCS
	g++ serverEE.cpp -g -std=c++11 -o serverEE
	g++ serverM.cpp -g -std=c++11 -o serverM

clean:
	rm -f client serverC serverCS serverEE serverM
